INSERT INTO`messages`(`text`,`response`) VALUES("how are you","I'm fine! Tell me about you?");
INSERT INTO`messages`(`text`,`response`) VALUES("how are you","I'm fine! Tell me about you?");
INSERT INTO`messages`(`text`,`response`) VALUES("how are you?","I'm fine! Tell me about you?");
INSERT INTO`messages`(`text`,`response`) VALUES("How are you?","I'm fine! Tell me about you?");
INSERT INTO`messages`(`text`,`response`) VALUES("i'm aslo fine","Great");
INSERT INTO`messages`(`text`,`response`) VALUES("I'm aslo fine","Great");
INSERT INTO`messages`(`text`,`response`) VALUES("Fine","Great");
INSERT INTO`messages`(`text`,`response`) VALUES("Good","Great");
INSERT INTO`messages`(`text`,`response`) VALUES("I need a help","How may I help you?");
INSERT INTO`messages`(`text`,`response`) VALUES("Is there have resonable holiday package","Of course..We have a lots of Holiday Plan..Go and Checkout");
INSERT INTO`messages`(`text`,`response`) VALUES("Any package","Of course..We have a lots of Holiday Plan..Go and Checkout");
INSERT INTO`messages`(`text`,`response`) VALUES("Is there have resonable holiday package?","Of course..We have a lots of Holiday Plan..Go and Checkout");
INSERT INTO`messages`(`text`,`response`) VALUES("Holiday package","Of course..We have a lots of Holiday Plan..Go and Checkout");
INSERT INTO`messages`(`text`,`response`) VALUES("Any package?","Of course..We have a lots of Holiday Plan..Go and Checkout");
INSERT INTO`messages`(`text`,`response`) VALUES("Who are you?","I'm a chatbot");
INSERT INTO`messages`(`text`,`response`) VALUES("How you suggest the holiday plans","We suggest tourist places Division wise");
INSERT INTO`messages`(`text`,`response`) VALUES("Is there have any rating option?","Of course..You can check top of the page");
INSERT INTO`messages`(`text`,`response`) VALUES("This is only for Bangladesh Tourist?","Yes..There have all the details of Bangladesh tourist places");
INSERT INTO`messages`(`text`,`response`) VALUES("thanks","Most Welcome!! See you again");
INSERT INTO`messages`(`text`,`response`) VALUES("Thanks","Most Welcome!! See you again");
INSERT INTO`messages`(`text`,`response`) VALUES("Thank you","Most Welcome!! See you again");
INSERT INTO`messages`(`text`,`response`) VALUES("thank you","Most Welcome!! See you again");
INSERT INTO`messages`(`text`,`response`) VALUES("thnx","Most Welcome!! See you again");
INSERT INTO`messages`(`text`,`response`) VALUES("ok","Okay!! Have a nice day");
INSERT INTO`messages`(`text`,`response`) VALUES("Ok","Okay!! Have a nice day");
INSERT INTO`messages`(`text`,`response`) VALUES("Okay","Okay!! Have a nice day");
INSERT INTO`messages`(`text`,`response`) VALUES("okay","Okay!! Have a nice day");
INSERT INTO`messages`(`text`,`response`) VALUES("Dhaka","Yeah there have dhaka too");